---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver on ansible nodes
    apt:
        name: apache2
        state: present

  - name: i want to start webserver
    services: 
       name: apache2
       state: started